aboot: Add missing `stdint.h` include
Without this include, builds on musl systems end up with the following
error:

```
src/libostree/ostree-bootloader-aboot.c:136:18: error: 'uintptr_t'
    undeclared (first use in this function)
  136 |   int fd = (int)(uintptr_t)data;
      |                  ~~~~~~~~
```