config/set: Don't fail when setting negative value
Some config options have special meaning when the value is negative. For
example, `core.lock-timeout-secs` when set to -1 means timeout disabled.
Currently, `g_option_context_parse` fails when parsing negative values:
```
ostree config set core.lock-timeout-secs -1
error: Unknown option -1
```
We need to tell it to ignore unknown options instead of erroring out and
let the `ostree_builtin_config` code handle the value properly.

Fixes #1893

Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>